### ISSUE TITLE
Why building with --with-pdcurses requires X libraries?

### ISSUE THREAD

**Issue by EGYPHARAOH** [ThomasDickey/cdk-snapshots#6]
I have does the following conf command:
 ./configure --with-pdcurses -without-x --without-curses-colr --without-curses-5lib --without-Xaw3d --without-Xaw3dxft  --without-neXtaw  --without-XawPlus --enable-hdr-subdir --enable-const --with-warnings --prefix=/cdk_static

it gave complains about:

checking for X... disabled
checking if you want to link with Xaw 3d library... no
checking if you want to link with Xaw 3d xft library... no
checking if you want to link with neXT Athena library... no
checking if you want to link with Athena-Plus library... no
checking for XextCreateExtension in -lXext... no
configure: WARNING: unable to find X11 library
configure: WARNING: unable to find ICE library
configure: WARNING: unable to find SM library
configure: WARNING: unable to find Xt library
checking for XOpenDisplay... no
checking for XOpenDisplay in -lX11... no
checking for XtAppInitialize... no
checking for XtAppInitialize in -lXt... no
configure: WARNING: Unable to successfully link X Toolkit library (-lXt) with
test program.  You will have to check and add the proper libraries by hand
to makefile.
checking for X11/Xaw/SimpleMenu.h... no
checking for X11/Xaw/SimpleMenu.h in /usr/contrib/X11R6... no
checking for X11/Xaw/SimpleMenu.h in /usr/contrib/X11R5... no
checking for X11/Xaw/SimpleMenu.h in /usr/lib/X11R5... no
checking for X11/Xaw/SimpleMenu.h in /usr/local... no
configure: WARNING: Unable to successfully find Athena header files with test program
checking for XawSimpleMenuAddGlobalActions in -lXaw -lXmu... no
checking for XawSimpleMenuAddGlobalActions in -lXaw -lXpm -lXmu... no
checking for XawSimpleMenuAddGlobalActions in -lXaw_s -lXmu_s... no
checking for XawSimpleMenuAddGlobalActions in -lXaw7 -lXmu... no
checking for XawSimpleMenuAddGlobalActions in -lXaw7 -lXpm -lXmu... no
checking for XawSimpleMenuAddGlobalActions in -lXaw7_s -lXmu_s... no
checking for XawSimpleMenuAddGlobalActions in -lXaw6 -lXmu... no
checking for XawSimpleMenuAddGlobalActions in -lXaw6 -lXpm -lXmu... no
checking for XawSimpleMenuAddGlobalActions in -lXaw6_s -lXmu_s... no
checking for -lXaw -lXmu in /usr/contrib/X11R6... no
checking for -lXaw -lXpm -lXmu in /usr/contrib/X11R6... no
checking for -lXaw_s -lXmu_s in /usr/contrib/X11R6... no
checking for -lXaw7 -lXmu in /usr/contrib/X11R6... no
checking for -lXaw7 -lXpm -lXmu in /usr/contrib/X11R6... no
checking for -lXaw7_s -lXmu_s in /usr/contrib/X11R6... no
checking for -lXaw6 -lXmu in /usr/contrib/X11R6... no
checking for -lXaw6 -lXpm -lXmu in /usr/contrib/X11R6... no
checking for -lXaw6_s -lXmu_s in /usr/contrib/X11R6... no
checking for -lXaw -lXmu in /usr/contrib/X11R5... no
checking for -lXaw -lXpm -lXmu in /usr/contrib/X11R5... no
checking for -lXaw_s -lXmu_s in /usr/contrib/X11R5... no
checking for -lXaw7 -lXmu in /usr/contrib/X11R5... no
checking for -lXaw7 -lXpm -lXmu in /usr/contrib/X11R5... no
checking for -lXaw7_s -lXmu_s in /usr/contrib/X11R5... no
checking for -lXaw6 -lXmu in /usr/contrib/X11R5... no
checking for -lXaw6 -lXpm -lXmu in /usr/contrib/X11R5... no
checking for -lXaw6_s -lXmu_s in /usr/contrib/X11R5... no
checking for -lXaw -lXmu in /usr/lib/X11R5... no
checking for -lXaw -lXpm -lXmu in /usr/lib/X11R5... no
checking for -lXaw_s -lXmu_s in /usr/lib/X11R5... no
checking for -lXaw7 -lXmu in /usr/lib/X11R5... no
checking for -lXaw7 -lXpm -lXmu in /usr/lib/X11R5... no
checking for -lXaw7_s -lXmu_s in /usr/lib/X11R5... no
checking for -lXaw6 -lXmu in /usr/lib/X11R5... no
checking for -lXaw6 -lXpm -lXmu in /usr/lib/X11R5... no
checking for -lXaw6_s -lXmu_s in /usr/lib/X11R5... no
checking for -lXaw -lXmu in /usr/local... no
checking for -lXaw -lXpm -lXmu in /usr/local... no
checking for -lXaw_s -lXmu_s in /usr/local... no
checking for -lXaw7 -lXmu in /usr/local... no
checking for -lXaw7 -lXpm -lXmu in /usr/local... no
checking for -lXaw7_s -lXmu_s in /usr/local... no
checking for -lXaw6 -lXmu in /usr/local... no
checking for -lXaw6 -lXpm -lXmu in /usr/local... no
checking for -lXaw6_s -lXmu_s in /usr/local... no
configure: error: Unable to successfully link Athena library (-lXaw) with test program

why compiling for PDcurses requires X11 stuff?
is there a way to get over that?
Building enviorment is Msys2 Mingw-w64
with working static pdcurses.lib pdcurses.a
been tested (the pdcurses library

**Comment by ThomasDickey** [comment]
If you want to build it with that configuration, you might want to provide a patch.

**Comment by EGYPHARAOH** [comment]
Hi first of all thank you for your reply
Ok Sir I have to admit (publicly) that I am very new to this domain, What patch? is it some file that I will download and apply to the package or is it something I should write?
 I have tried to read the configure script before I open the issue on the hope that I will comment some lines or even blocks and it might work
But I colided with2 facts
1) I have no idea about the scripting language it is written with (I know it is sh script works under bash or sh)
2) after looking in some source files things became too complicated for me to do it on my own
so what do u suggest on me ?
(keep in your mind you will instruct a noob :) )

**Comment by ThomasDickey** [comment]
As a starting point, I'd look at the environment variables which the script would append-to: **`CFLAGS`**, **`CPPFLAGS`**, **`LDFLAGS`** and **`LIBS`**.  Ignoring the **`--with-pdcurses`** option, if you have a usable curses-library that can be linked using the options in those variables, it won't look for another curses library, e.g.,

export CPPFLAGS="-I _includepath_" 
export LIBS="-l _curseslibrary_"
cc -o foo foo.c $CPPFLAGS $LIBS

(with MinGW, the _curseslibrary_ would be the import-library).

**Comment by EGYPHARAOH** [comment]
Hello Sir and thank you for your help
Here is my Msys64 env variables:

VSCMD_ARG_TGT_ARCH=x64
DevEnvDir=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\
USERDOMAIN=MMA-PC
OS=Windows_NT
__DOTNET_PREFERRED_BITNESS=64
VCToolsVersion=14.16.27023
COMMONPROGRAMFILES=C:\Program Files\Common Files
PROCESSOR_LEVEL=6
PSModulePath=C:\Program Files (x86)\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
ConEmuDrawHWND=0x00020B02
CommonProgramW6432=C:\Program Files\Common Files
WindowsSDK_ExecutablePath_x86=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\
ConEmuDrive=C:
INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt
FORCE_NEW_WND=NO
!ExitCode=00000001
ConEmuPath="C:\Program Files\ConEmu\ConEmu\ConEmuC64.exe"
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
VSCMD_ARG_app_plat=Desktop
MSYSCON=mintty.exe
LANG=en_US.UTF-8
TZ=Africa/Cairo
VS150COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools\
MSYSTEM_CARCH=x86_64
HOSTNAME=MMA-PC
PUBLIC=C:\Users\Public
OLDPWD=/d/gitrepo
CONFIG_SITE=/mingw64/etc/config.site
ConEmuArgs2=
WindowsSdkBinPath=C:\Program Files (x86)\Windows Kits\10\bin\
VCToolsInstallDir=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\
MSYSTEM_CHOST=x86_64-w64-mingw32
FrameworkVersion64=v4.0.30319
USERNAME=MMA
ChocolateyInstall=C:\ProgramData\chocolatey
LOGONSERVER=\\MMA-PC
PROCESSOR_ARCHITECTURE=AMD64
VCIDEInstallDir=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\
tmp=C:\Users\MMA\AppData\Local\Temp
ConEmuPalette=<ConEmu>
LOCALAPPDATA=C:\Users\MMA\AppData\Local
ConEmuHooks=Enabled
COMPUTERNAME=MMA-PC
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
USER=MMA
WindowsLibPath=C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.17763.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.17763.0
!::=::\
SYSTEMDRIVE=C:
USERPROFILE=C:\Users\MMA
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW
SYSTEMROOT=C:\WINDOWS
USERDOMAIN_ROAMINGPROFILE=MMA-PC
ConEmuDir=C:\Program Files\ConEmu
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 23 Stepping 10, GenuineIntel
ANSICON_DEF=7
ConEmuArgs=
MINGW_PACKAGE_PREFIX=mingw-w64-x86_64
OneDriveConsumer=D:\MMA\OneDrive
PWD=/d/gitrepo/cdk-5.0-20190303
HOME=/home/MMA
__DOTNET_ADD_64BIT=1
TMP=/tmp
ConEmuWorkDir=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
ExtensionSdkDir=C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs
WindowsSDK_ExecutablePath_x64=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\
VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\
MSYS2_PATH_TYPE=inherit
Platform=x64
ConEmuANSI=ON
CommandPromptType=Native
ConEmuTask=<Startup>
MSYSTEM_PREFIX=/mingw64
FrameworkDir=C:\Windows\Microsoft.NET\Framework64\
VSCMD_ARG_HOST_ARCH=x64
OneDrive=D:\MMA\OneDrive
ConEmuAnsiLog=
VisualStudioVersion=15.0
!C:=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
PROCESSOR_REVISION=170a
FPS_BROWSER_USER_PROFILE_STRING=Default
WindowsSDKLibVersion=10.0.17763.0\
VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\
LIB=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\lib\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64;
LIBPATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\lib\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\lib\x86\store\references;C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.17763.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.17763.0;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;
VSCMD_VER=15.0
PROMPT=$P$G
NUMBER_OF_PROCESSORS=2
ProgramW6432=C:\Program Files
ConEmuCfgDir=C:\Users\MMA\AppData\Roaming
ConEmuWorkDrive=C:
ConEmuBackHWND=0x002309C8
WindowsSdkDir=C:\Program Files (x86)\Windows Kits\10\
NETFXSDKDir=C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\
COMSPEC=C:\WINDOWS\System32\cmd.exe
ConEmuConfig=
ConEmuHWND=0x00190AF2
APPDATA=C:\Users\MMA\AppData\Roaming
SHELL=/usr/bin/bash
TERM=xterm
WindowsSdkVerBinPath=C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\
WindowsSDKVersion=10.0.17763.0\
UCRTVersion=10.0.17763.0
WINDIR=C:\WINDOWS
MINGW_CHOST=x86_64-w64-mingw32
ProgramData=C:\ProgramData
SHLVL=1
PRINTER=HP LaserJet 2430 PCL6 Class Driver
ACLOCAL_PATH=/mingw64/share/aclocal:/usr/share/aclocal
PROGRAMFILES=C:\Program Files
FrameworkVersion=v4.0.30319
ConEmuBaseDir=C:\Program Files\ConEmu\ConEmu
MANPATH=/mingw64/local/man:/mingw64/share/man:/usr/local/man:/usr/share/man:/usr/man:/share/man
ORIGINAL_TEMP=/c/Users/MMA/AppData/Local/Temp
ORIGINAL_TMP=/c/Users/MMA/AppData/Local/Temp
ConEmuC2="C:\Program Files\ConEmu\ConEmu\ConEmuC.exe"
ConEmuC3=ConEmuC64.exe
ConEmuC1="C:\Program Files\ConEmu\ConEmu\ConEmuC64.exe"
ALLUSERSPROFILE=C:\ProgramData
TEMP=/tmp
temp=C:\Users\MMA\AppData\Local\Temp
__VSCMD_PREINIT_PATH=C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;d:\OCamlPro\OCPWin\wrappers;d:\OCamlPro\OCPWin\4.02.1+ocp1-msvc64-20160113\bin;C:\Perl64\site\bin;C:\Perl64\bin;D:\Python37\Scripts\;D:\Python37\;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;c:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\PostgreSQL\pg11\bin;C:\nodejs\;C:\ProgramData\chocolatey\bin;D:\CMake\bin;D:\Program Files\Meson\;d:\TDM-GCC-64\bin;d:\Program Files\Git\cmd;C:\Users\MMA\AppData\Local\Microsoft\WindowsApps;C:\Users\MMA\AppData\Roaming\npm;d:\GTK+-Bundle-3.6.1\bin;d:\gtk-3.8.1;C:\Program Files\doxygen\bin;d:\LLVM-8\bin;D:\Program Files\Hercules\R3.13;d:\OCamlPro\OCPWin\wrappers;d:\OCamlPro\OCPWin\4.02.1+ocp1-msvc64-20160113\bin;C:\Users\MMA\AppData\Local\Microsoft\WindowsApps;C:\Users\MMA\AppData\Roaming\npm;d:\gtk-3.8.1
DriverData=C:\Windows\System32\Drivers\DriverData
MSYSTEM=MINGW64
MINGW_PREFIX=/mingw64
UniversalCRTSdkDir=C:\Program Files (x86)\Windows Kits\10\
SESSIONNAME=Console
ConEmuBuild=190310
IFCPATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\ifc\x64
ProgramFiles(x86)=C:\Program Files (x86)
PATH=/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64:/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/Common7/IDE/CommonExtensions/Microsoft/TestWindow:/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/bin/Roslyn:/c/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.6.1 Tools/x64:/c/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x64:/c/Program Files (x86)/Windows Kits/10/bin/x64:/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/bin:/c/Windows/Microsoft.NET/Framework64/v4.0.30319:/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/Common7/IDE:/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/Common7/Tools:/c/Program Files/ConEmu/ConEmu/Scripts:/c/Program Files/ConEmu:/c/Program Files/ConEmu/ConEmu:/d/OCamlPro/OCPWin/wrappers:/d/OCamlPro/OCPWin/4.02.1+ocp1-msvc64-20160113/bin:/c/Perl64/site/bin:/c/Perl64/bin:/d/Python37/Scripts:/d/Python37:/c/Python27:/c/Python27/Scripts:/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/Program Files/Microsoft VS Code/bin:/c/PostgreSQL/pg11/bin:/c/nodejs:/c/ProgramData/chocolatey/bin:/d/CMake/bin:/d/Program Files/Meson:/d/TDM-GCC-64/bin:/d/Program Files/Git/cmd:/c/Users/MMA/AppData/Local/Microsoft/WindowsApps:/c/Users/MMA/AppData/Roaming/npm:/d/GTK+-Bundle-3.6.1/bin:/d/gtk-3.8.1:/c/Program Files/doxygen/bin:/d/LLVM-8/bin:/d/Program Files/Hercules/R3.13:/d/OCamlPro/OCPWin/wrappers:/d/OCamlPro/OCPWin/4.02.1+ocp1-msvc64-20160113/bin:/c/Users/MMA/AppData/Local/Microsoft/WindowsApps:/c/Users/MMA/AppData/Roaming/npm:/d/gtk-3.8.1:/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin:/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
ConEmuPID=10232
PS1=\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[35m\]$MSYSTEM\[\e[0m\] \[\e[33m\]\w\[\e[0m\]\n\$
WIX=C:\Program Files (x86)\WiX Toolset v3.11\
HOMEDRIVE=C:
ConEmuBaseDirShort=C:\PROGRA~1\ConEmu\ConEmu
ChocolateyLastPathUpdate=Thu Feb 21 18:47:28 2019
PKG_CONFIG_PATH=/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig
INFOPATH=/usr/local/info:/usr/share/info:/usr/info:/share/info
HOMEPATH=\Users\MMA
Framework40Version=v4.0
ORIGINAL_PATH=/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64:/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/Common7/IDE/CommonExtensions/Microsoft/TestWindow:/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/bin/Roslyn:/c/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.6.1 Tools/x64:/c/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x64:/c/Program Files (x86)/Windows Kits/10/bin/x64:/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/bin:/c/Windows/Microsoft.NET/Framework64/v4.0.30319:/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/Common7/IDE:/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/Common7/Tools:/c/Program Files/ConEmu/ConEmu/Scripts:/c/Program Files/ConEmu:/c/Program Files/ConEmu/ConEmu:/d/OCamlPro/OCPWin/wrappers:/d/OCamlPro/OCPWin/4.02.1+ocp1-msvc64-20160113/bin:/c/Perl64/site/bin:/c/Perl64/bin:/d/Python37/Scripts:/d/Python37:/c/Python27:/c/Python27/Scripts:/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/Program Files/Microsoft VS Code/bin:/c/PostgreSQL/pg11/bin:/c/nodejs:/c/ProgramData/chocolatey/bin:/d/CMake/bin:/d/Program Files/Meson:/d/TDM-GCC-64/bin:/d/Program Files/Git/cmd:/c/Users/MMA/AppData/Local/Microsoft/WindowsApps:/c/Users/MMA/AppData/Roaming/npm:/d/GTK+-Bundle-3.6.1/bin:/d/gtk-3.8.1:/c/Program Files/doxygen/bin:/d/LLVM-8/bin:/d/Program Files/Hercules/R3.13:/d/OCamlPro/OCPWin/wrappers:/d/OCamlPro/OCPWin/4.02.1+ocp1-msvc64-20160113/bin:/c/Users/MMA/AppData/Local/Microsoft/WindowsApps:/c/Users/MMA/AppData/Roaming/npm:/d/gtk-3.8.1:/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin:/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja
FrameworkDir64=C:\Windows\Microsoft.NET\Framework64\
ConEmuServerPID=10472
VCToolsRedistDir=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Redist\MSVC\14.16.27012\
ANSICON=159x32766 (159x35)
_=/usr/bin/env
I have noticed that I am missing the CPPFLAGS and the LIBS 
so I issued the following 2 commands
 export CPPFLAGS="-l /mingw64/include"
&&
 export LIBS="-l /mingw64/lib"
and doing 'ls /mingw64/include' will show:
ansidecl.h  bfd.h  bfdlink.h  **_curses.h_**  dis-asm.h  **_panel.h_**  plugin-api.h  regex.h  symcat.h  **_term.h_**
the 3 marked (by bold and itlaic) files r the includes related to my curses lib
and doing 'ls /mingw64/lib' show
gcc  gnurx.lib  gnurx.lib.blah  libbfd.a  libgnurx.dll.a  libopcodes.a  libregex.a  **_pdcurses.lib_**
and finally doing 'gcc --version' show:
 gcc --version
gcc.exe (tdm64-1) 5.1.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

i do not have cc as neither executable not alias for an executable
where I should head to from here?
the aim is to get the cdk as static (most important) and as dynamic ".dll" (wishful thinking) in 2 different compilation sessions so I can use them later in my supreme dream of turning it into php_cdk.dll 
PHP extension

**Comment by EGYPHARAOH** [comment]
Also, I do not know if the following info could make it any better, I still see its worth mentioning:
Obviously the curses lib I count on does not have forms.h as ncurses does
also if you opened the term.h you will find the following comment into it:
/* Public Domain Curses */

/* PDCurses doesn't operate with terminfo, but we need these functions for 
   compatibility, to allow some things (notably, interface libraries for 
   other languages) to be compiled. Anyone who tries to actually _use_ 
   them will be disappointed, since they only return ERR. */
___________________________________________________________________________________________________
I have included the whole thing in attachment to this message, because I do not know if missing forms.h means there functions are also missing or they have been inclded in one of the other 2 .h files....
[pdcurses_lib.zip](https://github.com/ThomasDickey/cdk-snapshots/files/3050832/pdcurses_lib.zip)
Thank you again

**Comment by ThomasDickey** [comment]
Cdk doesn't use the forms-library (just plain curses).  It could be improved by using the panel-library, but that's a different matter.

What I meant by the environment variables, was (for example) constructing a simple script that sets the $CPPFLAGS and $LIBS variables to fool the configure script into thinking that it's done the checks, and making that a workable configuration for compiling Cdk.

**Comment by EGYPHARAOH** [comment]
hello sir
I have done the following
$export CPPFLAGS=-I/D/pdcurses_lib/include/
$ export LDFLAGS/D/pdcurses_lib/lib/pdcurses.lib
or
$ export LDFLAGS=-L/D/pdcurses_lib/lib/pdcurses.a
or
$ export LDFLAGS=-L/D/pdcurses_lib/lib/
in the 3 cases
when i do
$./configure

I get the following endings:

checking if we have identified curses headers... (cached) curses.h
checking for curses.h... (cached) yes
checking for terminfo header... (cached) unknown
checking for ncurses version... no
checking if we have identified curses libraries... no
checking for tgoto... no
checking for tgoto in -lcursesX... no
checking for tgoto in -lcurses... no
checking for tgoto in -lncurses... no
checking for tgoto in -lotermcap... no
checking for tgoto in -ltermcap... no
checking for tgoto in -ltinfo... no
checking for tgoto in -ltermlib... no
checking for tgoto in -lunknown... no
checking if we can link with cursesX library... no
checking if we can link with curses library... no
checking if we can link with ncurses library... no
checking if we can link with xcurses library... no
checking if we can link with jcurses library... no
checking if we can link with pdcurses library... no
checking if we can link with unknown library... no
configure: error: no curses library found

where should I go from here?
and sorry for the delay I was unstable health wise

**Comment by EGYPHARAOH** [comment]
in the following the attched configure.log of latest trial
[config.log](https://github.com/ThomasDickey/cdk-snapshots/files/3095290/config.log)

**Comment by EGYPHARAOH** [comment]
I have reread the conversation and found out that first you suggested LIBS="-l....."
so I did the following
$ export LIBS="-l D:/pdcurses_lib/lib/pdcurses.lib"
OR
$ export LIBS="-l D:/pdcurses_lib/lib/pdcurses.a"
OR
$ export LIBS="-l D:/pdcurses_lib/lib/pdcurses"
and i have done 
$unset LDFLAGS
the result of the 3 cases
is gcc cant compile
and the following attach is config.log
[config.log](https://github.com/ThomasDickey/cdk-snapshots/files/3095470/config.log)

**Comment by EGYPHARAOH** [comment]
[config.log](https://github.com/ThomasDickey/cdk-snapshots/files/3095495/config.log)

**Comment by EGYPHARAOH** [comment]
OK this my last trial for today
with
$ export CPPFLAGS=-I/D/pdcurses_lib/include/
$ export LIBS="-L /d/pdcurses_lib/lib -lpdcurses"
$./configure
failed but I have noticed something
it faces problems with the lib itself
[config.log](https://github.com/ThomasDickey/cdk-snapshots/files/3095632/config.log)
